language: python
python:
  - "2.7"
before_install:
  - sudo apt-get install gfortran libopenblas-dev liblapack-dev python-dev
install:
  - pip install scipy
  - pip install -r requirements.txt
script: nosetests
